# Generated by Django 5.1.6 on 2025-02-22 11:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='cv_file',
            field=models.FileField(blank=True, null=True, upload_to='cv_files/'),
        ),
    ]
