# Generated by Django 5.1.6 on 2025-02-22 12:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_profile_cv_file'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='job_title',
            field=models.CharField(default='Urban Management and Development Specialist', max_length=100),
        ),
    ]
